/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cst4l;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author Mish
 */
public class ContextFreeGrammar extends javax.swing.JFrame {

    /**
     * Creates new form pushdownGUI
     */
    public ContextFreeGrammar() {
        initComponents();
        designComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbProdRule = new javax.swing.JComboBox<>();
        lblProdRule = new javax.swing.JLabel();
        lblInput = new javax.swing.JLabel();
        tfInput = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnValidate = new javax.swing.JButton();
        jsDiv = new javax.swing.JSeparator();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taResult = new javax.swing.JTextArea();
        windowBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Context-Free Grammar");
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Context-Free Grammar");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 370, 60));

        cmbProdRule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S -> aSb", "S -> aSa | bSb | ε", "S -> aSa | bSb | c" }));
        panel.add(cmbProdRule, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 310, -1));

        lblProdRule.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProdRule.setForeground(new java.awt.Color(237, 161, 54));
        lblProdRule.setText("Select a Production Rule:");
        lblProdRule.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(lblProdRule, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 169, -1));

        lblInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInput.setForeground(new java.awt.Color(237, 161, 54));
        lblInput.setText("Enter string to be validated:");
        panel.add(lblInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 221, -1));

        tfInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputActionPerformed(evt);
            }
        });
        panel.add(tfInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 310, -1));

        btnClear.setBackground(new java.awt.Color(237, 161, 54));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        panel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 90, 30));

        btnValidate.setBackground(new java.awt.Color(237, 161, 54));
        btnValidate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnValidate.setForeground(new java.awt.Color(255, 255, 255));
        btnValidate.setText("Validate String");
        btnValidate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateActionPerformed(evt);
            }
        });
        panel.add(btnValidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 310, 30));
        panel.add(jsDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 310, 10));

        btnBack.setBackground(new java.awt.Color(237, 161, 54));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        btnBack.setText(" Back");
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        panel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        btnExit.setBackground(new java.awt.Color(237, 161, 54));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 90, 30));

        lblResult.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResult.setForeground(new java.awt.Color(237, 161, 54));
        lblResult.setText("Result");
        panel.add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 182, -1));

        taResult.setEditable(false);
        taResult.setColumns(20);
        taResult.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taResult.setRows(2);
        taResult.setTabSize(1);
        taResult.setAutoscrolls(false);
        jScrollPane2.setViewportView(taResult);

        panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 328, 310, 70));

        windowBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bgCFG.png"))); // NOI18N
        windowBg.setText("jLabel4");
        panel.add(windowBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tfInput.setText("");
        taResult.setText("");
        cmbProdRule.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new MainDashboard().setVisible(true); 
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateActionPerformed
        String result = "";
        String input = tfInput.getText().trim();
        String selectedRule = (String) cmbProdRule.getSelectedItem();

        if (selectedRule == null || selectedRule.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a Product Rule.",
                    "No Production Rule Selected", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a string.",
                    "No String Entered", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean isValid = validateString(input, selectedRule);
        if (isValid) {
            result += "Input: " + input + "\n";
            result += "String is Accepted!";
            taResult.setText(result);
        } else {
            result += "Input: " + input + "\n";
            result += "String is Rejeced!";
            taResult.setText(result);
        }
    }//GEN-LAST:event_btnValidateActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Exit program?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void tfInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputActionPerformed
    
    public static boolean validateString(String input, String productionRule) {
        switch (productionRule) {
            case "S -> aSb":
                return validateASb(input); 
            case "S -> aSa | bSb | ε":
                return validateASaBSbEpsilon(input);
            case "S -> aSa | bSb | c":
                return validateASaBSbC(input);
            default:
                return false;
        }
    }
    
    public static boolean validateASb(String str) {
        if (str.isEmpty()) {
            return true; // Base case for ε
        }

        if (str.length() < 2) {
            return false; // Reject strings like "a" or "b" or invalid lengths
        }

        char first = str.charAt(0);
        char last = str.charAt(str.length() - 1);

        // Ensure the first and last characters are 'a' and 'b' respectively
        if (first == 'a' && last == 'b') {
            return validateASb(str.substring(1, str.length() - 1)); // Recursive check
        }

        return false; // Reject if it doesn't match the pattern
    }
    
    public static boolean validateASaBSbEpsilon(String str) {
        if (str.isEmpty()) {
            return true; // ε case
        }

        if (str.length() < 2) {
            return false; // Strings like "a" or "b" cannot be valid
        }

        char first = str.charAt(0);
        char last = str.charAt(str.length() - 1);

        if ((first == 'a' && last == 'a') || (first == 'b' && last == 'b')) {
            return validateASaBSbEpsilon(str.substring(1, str.length() - 1));
        }

        return false; // Reject if characters do not match the rule
    }

    public static boolean validateASaBSbC(String str) {
        if (str.isEmpty()) {
            return false;
        }

        if (str.equals("c")) {
            return true;
        }

        if (str.length() < 3) {
            return false;
        }

        char first = str.charAt(0);
        char last = str.charAt(str.length() - 1);

        if ((first == 'a' && last == 'a') || (first == 'b' && last == 'b')) {
            return validateASaBSbC(str.substring(1, str.length() - 1));
        }

        return false;
    }
    
    private void designComponents() {
        // Set icon image for the program
        //ImageIcon img = new ImageIcon("src/icon.png");
        //this.setIconImage(img.getImage());
        // Center window when running
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2 - 25);
        this.setLocation(x, y);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContextFreeGrammar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContextFreeGrammar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContextFreeGrammar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContextFreeGrammar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        FlatLightLaf.registerCustomDefaultsSource("style");
        FlatLightLaf.setup();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContextFreeGrammar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnValidate;
    private javax.swing.JComboBox<String> cmbProdRule;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jsDiv;
    private javax.swing.JLabel lblInput;
    private javax.swing.JLabel lblProdRule;
    private javax.swing.JLabel lblResult;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea taResult;
    private javax.swing.JTextField tfInput;
    private javax.swing.JLabel windowBg;
    // End of variables declaration//GEN-END:variables
}
