/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cst4l;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mish
 */
public class DeterministicFA extends javax.swing.JFrame {

    /**
     * Creates new form pushdownGUI
     */
    
    private String inputString;
    private int inputIndex;
    private int currentState;
    private Map<Integer, Map<String, Integer>> transitions;
    private DefaultTableModel tableModel;
    private static final int DEAD_STATE = -1; // Dead state represented as -1
    
    public DeterministicFA() {
        initComponents();
        designComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransition = new javax.swing.JTable();
        lblTransitionTable = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbCriteria = new javax.swing.JComboBox<>();
        lblCriteria = new javax.swing.JLabel();
        lblInput = new javax.swing.JLabel();
        tfInput = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnSimulate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblOutput = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        windowBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deterministic Finite Automaton");
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTransition.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "State", "Input 0", "Input 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTransition);
        if (tblTransition.getColumnModel().getColumnCount() > 0) {
            tblTransition.getColumnModel().getColumn(0).setResizable(false);
            tblTransition.getColumnModel().getColumn(1).setResizable(false);
            tblTransition.getColumnModel().getColumn(2).setResizable(false);
        }

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 310, 150));

        lblTransitionTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTransitionTable.setForeground(new java.awt.Color(97, 125, 193));
        lblTransitionTable.setText("Transition Table:");
        panel.add(lblTransitionTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 182, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FINITE AUTOMATON");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 490, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("---------- DETERMINISTIC -------------");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 15, 490, 30));

        cmbCriteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Starts with '10'", "Contains '01'", "Ends with '11'" }));
        panel.add(cmbCriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 310, -1));

        lblCriteria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCriteria.setForeground(new java.awt.Color(97, 125, 193));
        lblCriteria.setText("DFA will accept strings that:");
        lblCriteria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(lblCriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 169, -1));

        lblInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInput.setForeground(new java.awt.Color(97, 125, 193));
        lblInput.setText("Enter string:");
        panel.add(lblInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 221, -1));

        tfInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputActionPerformed(evt);
            }
        });
        panel.add(tfInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 310, -1));

        btnClear.setBackground(new java.awt.Color(97, 125, 193));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        panel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 90, 30));

        btnSimulate.setBackground(new java.awt.Color(97, 125, 193));
        btnSimulate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimulate.setForeground(new java.awt.Color(255, 255, 255));
        btnSimulate.setText("Simulate");
        btnSimulate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimulate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimulateActionPerformed(evt);
            }
        });
        panel.add(btnSimulate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 310, 30));

        btnBack.setBackground(new java.awt.Color(97, 125, 193));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        btnBack.setText(" Back");
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        panel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        btnExit.setBackground(new java.awt.Color(97, 125, 193));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 90, 30));

        lblOutput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOutput.setForeground(new java.awt.Color(97, 125, 193));
        lblOutput.setText("Output");
        panel.add(lblOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 182, -1));

        taOutput.setEditable(false);
        taOutput.setColumns(20);
        taOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taOutput.setRows(2);
        taOutput.setTabSize(1);
        taOutput.setAutoscrolls(false);
        jScrollPane2.setViewportView(taOutput);

        panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 240, 310));

        windowBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bgDFA.png"))); // NOI18N
        panel.add(windowBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        DefaultTableModel model = (DefaultTableModel)tblTransition.getModel();
        model.setRowCount(0);
        tfInput.setText("");
        taOutput.setText("");
        cmbCriteria.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new MainDashboard().setVisible(true); 
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSimulateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimulateActionPerformed
        String criteria = (String) cmbCriteria.getSelectedItem();
        inputString = tfInput.getText().trim();
        
        if (inputString.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Input cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!inputString.matches("[01]+")) {
            JOptionPane.showMessageDialog(this, "Input must be a binary string (0s and 1s).", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Reset Transition Table
        DefaultTableModel model = (DefaultTableModel)tblTransition.getModel();
        model.setRowCount(0);
        
        initializeTransitions(criteria);
        updateTransitionTable();
        simulateDFA(taOutput, criteria);
    }//GEN-LAST:event_btnSimulateActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Exit program?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void tfInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputActionPerformed
    
    private void initializeTransitions(String criteria) {
        transitions = switch (criteria) {
            case "Starts with '10'" -> getStartsWith10Transitions();
            case "Contains '01'" -> getContains01Transitions();
            case "Ends with '11'" -> getEndsWith11Transitions();
            default -> new HashMap<>();
        };
    }

    private Map<Integer, Map<String, Integer>> getStartsWith10Transitions() {
        Map<Integer, Map<String, Integer>> map = new HashMap<>();

        map.put(0, Map.of("1", 1, "0", DEAD_STATE));
        map.put(1, Map.of("0", 2, "1", DEAD_STATE));
        map.put(2, Map.of("0", 2, "1", 2));
        map.put(DEAD_STATE, Map.of("0", DEAD_STATE, "1", DEAD_STATE));

        return map;
    }

    private Map<Integer, Map<String, Integer>> getContains01Transitions() {
        Map<Integer, Map<String, Integer>> map = new HashMap<>();

        map.put(0, Map.of("0", 0, "1", 1));
        map.put(1, Map.of("0", 2, "1", 1));
        map.put(2, Map.of("0", 2, "1", 2));
        map.put(DEAD_STATE, Map.of("0", DEAD_STATE, "1", DEAD_STATE));

        return map;
    }

    private Map<Integer, Map<String, Integer>> getEndsWith11Transitions() {
        Map<Integer, Map<String, Integer>> map = new HashMap<>();

        map.put(0, Map.of("0", 0, "1", 1));
        map.put(1, Map.of("0", 0, "1", 2));
        map.put(2, Map.of("0", 0, "1", 2));
        map.put(DEAD_STATE, Map.of("0", DEAD_STATE, "1", DEAD_STATE));

        return map;
    }
    
    private void updateTransitionTable() {
        DefaultTableModel model = (DefaultTableModel)tblTransition.getModel();
        model.setRowCount(0);
        String[] states = {"q0", "q1", "q2", "qd"};

        for (int i = 0; i < states.length; i++) {
            Map<String, Integer> transition = transitions.getOrDefault(i, transitions.get(DEAD_STATE));
            model.addRow(new Object[]{
                states[i],
                transition.getOrDefault("0", DEAD_STATE) == DEAD_STATE ? "qd" : "q" + transition.get("0"),
                transition.getOrDefault("1", DEAD_STATE) == DEAD_STATE ? "qd" : "q" + transition.get("1")
            });
        }
    }

    private void simulateDFA(JTextArea taOutput, String criteria) {
        inputIndex = 0;
        currentState = 0;
        taOutput.setText("Starting DFA Simulation...\n");
        log(taOutput, "Input String: " + inputString);
        log(taOutput, "Criteria: " + criteria);
        log(taOutput, "Initial State: q0");

        Timer timer = new Timer(1000, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (inputIndex < inputString.length()) {
                    String symbol = String.valueOf(inputString.charAt(inputIndex));
                    currentState = transitions.getOrDefault(currentState, transitions.get(DEAD_STATE)).getOrDefault(symbol, DEAD_STATE);
                    log(taOutput, "Current State: " + (currentState == DEAD_STATE ? "qd" : "q" + currentState));
                    inputIndex++;
                } else {
                    ((Timer) e.getSource()).stop();
                    finalizeSimulation(criteria, taOutput);
                }
            }
        });
        timer.start();
    }

    private void finalizeSimulation(String criteria, JTextArea taOutput) {
        boolean accepted = switch (criteria) {
            case "Starts with '10'" -> currentState == 2;
            case "Contains '01'" -> currentState == 2;
            case "Ends with '11'" -> currentState == 2;
            default -> false;
        };

        String result = accepted ? "String Accepted!" : "String Rejected!";
        log(taOutput, result);
        JOptionPane.showMessageDialog(this, result, "Result", JOptionPane.INFORMATION_MESSAGE);
    }

    private void log(JTextArea taOutput, String message) {
        taOutput.append(message + "\n");
    }
    
    private void designComponents() {
        // Set icon image for the program
        //ImageIcon img = new ImageIcon("src/icon.png");
        //this.setIconImage(img.getImage());
        // Center window when running
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2 - 25);
        this.setLocation(x, y);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeterministicFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeterministicFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeterministicFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeterministicFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        FlatLightLaf.registerCustomDefaultsSource("style");
        FlatLightLaf.setup();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeterministicFA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSimulate;
    private javax.swing.JComboBox<String> cmbCriteria;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCriteria;
    private javax.swing.JLabel lblInput;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblTransitionTable;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea taOutput;
    private javax.swing.JTable tblTransition;
    private javax.swing.JTextField tfInput;
    private javax.swing.JLabel windowBg;
    // End of variables declaration//GEN-END:variables
}
