package cst4l;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

public class MainDashboard extends javax.swing.JFrame {

    /**
     * Creates new form TuringMachine
     */
    public MainDashboard() {
        initComponents();
        designComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        btnTOH = new javax.swing.JButton();
        btnTM = new javax.swing.JButton();
        btnCFG = new javax.swing.JButton();
        btnPDA = new javax.swing.JButton();
        btnNDFA = new javax.swing.JButton();
        btnDFA = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblFirstNum = new javax.swing.JLabel();
        windowBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CST4 Final Project");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("---------- CS PROFESSIONAL TRACK 1 ----------");
        jPanel1.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 450, 40));

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 1, 46)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("FINAL PROJECT");
        jPanel1.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 21, 470, 80));

        btnTOH.setBackground(new java.awt.Color(184, 71, 105));
        btnTOH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTOH.setForeground(new java.awt.Color(255, 255, 255));
        btnTOH.setText("Tower of Hanoi");
        btnTOH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTOH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTOHActionPerformed(evt);
            }
        });
        jPanel1.add(btnTOH, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 310, 40));

        btnTM.setBackground(new java.awt.Color(150, 97, 193));
        btnTM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTM.setForeground(new java.awt.Color(255, 255, 255));
        btnTM.setText("Turing Machine");
        btnTM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTMActionPerformed(evt);
            }
        });
        jPanel1.add(btnTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 310, 40));

        btnCFG.setBackground(new java.awt.Color(237, 161, 54));
        btnCFG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCFG.setForeground(new java.awt.Color(255, 255, 255));
        btnCFG.setText("Context-Free Grammar");
        btnCFG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCFG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCFGActionPerformed(evt);
            }
        });
        jPanel1.add(btnCFG, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 310, 40));

        btnPDA.setBackground(new java.awt.Color(77, 166, 113));
        btnPDA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPDA.setForeground(new java.awt.Color(255, 255, 255));
        btnPDA.setText("Pushdown Automata");
        btnPDA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDAActionPerformed(evt);
            }
        });
        jPanel1.add(btnPDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 310, 40));

        btnNDFA.setBackground(new java.awt.Color(97, 193, 191));
        btnNDFA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNDFA.setForeground(new java.awt.Color(255, 255, 255));
        btnNDFA.setText("Non-deterministic Finite Automata");
        btnNDFA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNDFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNDFAActionPerformed(evt);
            }
        });
        jPanel1.add(btnNDFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 310, 40));

        btnDFA.setBackground(new java.awt.Color(97, 125, 193));
        btnDFA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDFA.setForeground(new java.awt.Color(255, 255, 255));
        btnDFA.setText("Deterministic Finite Automata");
        btnDFA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDFAActionPerformed(evt);
            }
        });
        jPanel1.add(btnDFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 310, 40));

        btnExit.setBackground(new java.awt.Color(97, 125, 193));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 120, 30));

        lblFirstNum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFirstNum.setForeground(new java.awt.Color(97, 125, 193));
        lblFirstNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFirstNum.setText("Select one:");
        jPanel1.add(lblFirstNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 330, 40));

        windowBg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        windowBg.setForeground(new java.awt.Color(51, 51, 51));
        windowBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bgMainDashboard2.png"))); // NOI18N
        jPanel1.add(windowBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Exit program?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDFAActionPerformed
        this.dispose();
        new DeterministicFA().setVisible(true); 
    }//GEN-LAST:event_btnDFAActionPerformed

    private void btnNDFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNDFAActionPerformed
        this.dispose();
        new NonDeterministicFA().setVisible(true); 
    }//GEN-LAST:event_btnNDFAActionPerformed

    private void btnPDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDAActionPerformed
        this.dispose();
        new PushdownAutomata().setVisible(true); 
    }//GEN-LAST:event_btnPDAActionPerformed

    private void btnTOHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTOHActionPerformed
        this.dispose();
        new TowerOfHanoi().setVisible(true); 
    }//GEN-LAST:event_btnTOHActionPerformed

    private void btnTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTMActionPerformed
        this.dispose();
        new TuringMachine().setVisible(true); 
    }//GEN-LAST:event_btnTMActionPerformed

    private void btnCFGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCFGActionPerformed
        this.dispose();
        new ContextFreeGrammar().setVisible(true);
    }//GEN-LAST:event_btnCFGActionPerformed
    
    private void designComponents() {
        // Set icon image for the program
        //ImageIcon img = new ImageIcon("src/icon.png");
        //this.setIconImage(img.getImage());
        // Center window when running
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2 - 25);
        this.setLocation(x, y);
        
        addHoverEffects();
    }
    
    private void addHoverEffects() {
        btnDFA.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                // Change the button's background color or perform an action
                btnDFA.setLocation(btnDFA.getX() + 15, btnDFA.getY());
                btnDFA.setBackground(Color.decode("#4B6BB8"));
            }
            @Override
            public void mouseExited(MouseEvent e) {
                // Revert the button's background color
                btnDFA.setLocation(btnDFA.getX() - 15, btnDFA.getY());
                btnDFA.setBackground(Color.decode("#617dc1"));
                //A17D71
            }
        });

        btnNDFA.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                // Example: Disable another button when hovering
                btnNDFA.setLocation(btnNDFA.getX() + 15, btnNDFA.getY());
                btnNDFA.setBackground(Color.decode("#47B7B4"));
            }
            @Override
            public void mouseExited(MouseEvent e) {
                // Re-enable the other button
                btnNDFA.setLocation(btnNDFA.getX() - 15, btnNDFA.getY());
                btnNDFA.setBackground(Color.decode("#61c1bf"));
            }
        });

        btnCFG.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                // Change the button's background color or perform an action
                btnCFG.setLocation(btnCFG.getX() + 15, btnCFG.getY());
                btnCFG.setBackground(Color.decode("#EA9319"));
            }
            @Override
            public void mouseExited(MouseEvent e) {
                // Revert the button's background color
                btnCFG.setLocation(btnCFG.getX() - 15, btnCFG.getY());
                btnCFG.setBackground(Color.decode("#eda136"));
            }
        });

        btnPDA.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                // Example: Disable another button when hovering
                btnPDA.setLocation(btnPDA.getX() + 15, btnPDA.getY());
                btnPDA.setBackground(Color.decode("#439263"));
            }
            @Override
            public void mouseExited(MouseEvent e) {
                // Re-enable the other button
                btnPDA.setLocation(btnPDA.getX() - 15, btnPDA.getY());
                btnPDA.setBackground(Color.decode("#4da671"));
            }
        });
        
        btnTM.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                // Change the button's background color or perform an action
                btnTM.setLocation(btnTM.getX() + 15, btnTM.getY());
                btnTM.setBackground(Color.decode("#874BB8"));
            }
            @Override
            public void mouseExited(MouseEvent e) {
                // Revert the button's background color
                btnTM.setLocation(btnTM.getX() - 15, btnTM.getY());
                btnTM.setBackground(Color.decode("#9661c1"));
            }
        });

        btnTOH.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                // Example: Disable another button when hovering
                btnTOH.setLocation(btnTOH.getX() + 15, btnTOH.getY());
                btnTOH.setBackground(Color.decode("#A53F5E"));
            }
            @Override
            public void mouseExited(MouseEvent e) {
                // Re-enable the other button
                btnTOH.setLocation(btnTOH.getX() - 15, btnTOH.getY());
                btnTOH.setBackground(Color.decode("#b84769"));
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.registerCustomDefaultsSource("style");
        FlatLightLaf.setup();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCFG;
    private javax.swing.JButton btnDFA;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNDFA;
    private javax.swing.JButton btnPDA;
    private javax.swing.JButton btnTM;
    private javax.swing.JButton btnTOH;
    private javax.swing.JLabel lblFirstNum;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel windowBg;
    // End of variables declaration//GEN-END:variables
}
