/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cst4l;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mish
 */
public class NonDeterministicFA_Copy extends javax.swing.JFrame {

    /**
     * Creates new form pushdownGUI
     */
    
    private String inputString;
    private int inputIndex;
    private int currentState;
    private Map<Integer, Map<String, Set<Integer>>> transitions;
    private DefaultTableModel tableModel;
    private static final int DEAD_STATE = -1;
    
    public NonDeterministicFA_Copy() {
        initComponents();
        designComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransition = new javax.swing.JTable();
        lblTransitionTable = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbCriteria = new javax.swing.JComboBox<>();
        lblCriteria = new javax.swing.JLabel();
        lblInput = new javax.swing.JLabel();
        tfInput = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnValidate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblOutput = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        windowBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deterministic Finite Automaton");
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTransition.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "State", "Input 0", "Input 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTransition);
        if (tblTransition.getColumnModel().getColumnCount() > 0) {
            tblTransition.getColumnModel().getColumn(0).setResizable(false);
            tblTransition.getColumnModel().getColumn(1).setResizable(false);
            tblTransition.getColumnModel().getColumn(2).setResizable(false);
        }

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 310, 160));

        lblTransitionTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTransitionTable.setForeground(new java.awt.Color(97, 125, 193));
        lblTransitionTable.setText("Transition Table:");
        panel.add(lblTransitionTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 182, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FINITE AUTOMATON");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 490, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("---------- NON-DETERMINISTIC -------------");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 15, 490, 30));

        cmbCriteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ends with '11'", "Contains '110'", "Ends with '01'" }));
        panel.add(cmbCriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 310, -1));

        lblCriteria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCriteria.setForeground(new java.awt.Color(97, 125, 193));
        lblCriteria.setText("Select a Criteria:");
        lblCriteria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(lblCriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 169, -1));

        lblInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInput.setForeground(new java.awt.Color(97, 125, 193));
        lblInput.setText("Enter string:");
        panel.add(lblInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 221, -1));

        tfInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputActionPerformed(evt);
            }
        });
        panel.add(tfInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 310, -1));

        btnClear.setBackground(new java.awt.Color(97, 125, 193));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        panel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 90, 30));

        btnValidate.setBackground(new java.awt.Color(97, 125, 193));
        btnValidate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnValidate.setForeground(new java.awt.Color(255, 255, 255));
        btnValidate.setText("Validate");
        btnValidate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateActionPerformed(evt);
            }
        });
        panel.add(btnValidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 310, 30));

        btnBack.setBackground(new java.awt.Color(97, 125, 193));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        btnBack.setText(" Back");
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        panel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        btnExit.setBackground(new java.awt.Color(97, 125, 193));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 90, 30));

        lblOutput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOutput.setForeground(new java.awt.Color(97, 125, 193));
        lblOutput.setText("Output");
        panel.add(lblOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 182, -1));

        taOutput.setEditable(false);
        taOutput.setColumns(20);
        taOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taOutput.setRows(2);
        taOutput.setTabSize(1);
        taOutput.setAutoscrolls(false);
        jScrollPane2.setViewportView(taOutput);

        panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 240, 320));

        windowBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bgDFA.png"))); // NOI18N
        panel.add(windowBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        DefaultTableModel model = (DefaultTableModel)tblTransition.getModel();
        model.setRowCount(0);
        tfInput.setText("");
        taOutput.setText("");
        cmbCriteria.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new MainDashboard().setVisible(true); 
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateActionPerformed
        String criteria = (String) cmbCriteria.getSelectedItem();
        inputString = tfInput.getText().trim();
        
        if (inputString.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Input cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!inputString.matches("[01]+")) {
            JOptionPane.showMessageDialog(this, "Input must be a binary string (0s and 1s).", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Reset Transition Table
        DefaultTableModel model = (DefaultTableModel)tblTransition.getModel();
        model.setRowCount(0);
        
        initializeTransitions(criteria);
        updateTransitionTable();
        simulateNDFA(taOutput, criteria);
    }//GEN-LAST:event_btnValidateActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Exit program?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void tfInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputActionPerformed
    
    private void initializeTransitions(String criteria) {
        transitions = switch (criteria) {
            case "Ends with '11'" -> getEndsWith11Transitions();
            case "Contains '110'" -> getContains110Transitions();
            case "Ends with '01'" -> getEndsWith01Transitions();
            default -> new HashMap<>();
        };
    }

    private Map<Integer, Map<String, Set<Integer>>> getEndsWith11Transitions() {
        Map<Integer, Map<String, Set<Integer>>> map = new HashMap<>();

        map.put(0, Map.of("1", Set.of(1), "0", Set.of(0)));
        map.put(1, Map.of("1", Set.of(2), "0", Set.of(0)));
        map.put(2, Map.of("1", Set.of(2), "0", Set.of(0)));
        map.put(DEAD_STATE, Map.of("1", Set.of(DEAD_STATE), "0", Set.of(DEAD_STATE)));

        return map;
    }

    private Map<Integer, Map<String, Set<Integer>>> getContains110Transitions() {
        Map<Integer, Map<String, Set<Integer>>> map = new HashMap<>();

        map.put(0, Map.of("0", Set.of(0), "1", Set.of(1)));
        map.put(1, Map.of("0", Set.of(2), "1", Set.of(1)));
        map.put(2, Map.of("0", Set.of(2), "1", Set.of(3)));
        map.put(3, Map.of("0", Set.of(3), "1", Set.of(3)));
        map.put(DEAD_STATE, Map.of("0", Set.of(DEAD_STATE), "1", Set.of(DEAD_STATE)));

        return map;
    }

    private Map<Integer, Map<String, Set<Integer>>> getEndsWith01Transitions() {
        Map<Integer, Map<String, Set<Integer>>> map = new HashMap<>();

        map.put(0, Map.of("0", Set.of(0), "1", Set.of(1)));
        map.put(1, Map.of("0", Set.of(2), "1", Set.of(1)));
        map.put(2, Map.of("0", Set.of(0), "1", Set.of(1)));
        map.put(DEAD_STATE, Map.of("0", Set.of(DEAD_STATE), "1", Set.of(DEAD_STATE)));

        return map;
    }
    
    private void updateTransitionTable() {
        DefaultTableModel model = (DefaultTableModel) tblTransition.getModel();
        model.setRowCount(0);  // Clear existing rows

        // State labels for each state
        String[] stateLabels = {"q0", "q1", "q2", "qd"};  // Adjust if you have more states

        // Iterate over the states and update the transition table
        for (int i = 0; i < stateLabels.length; i++) {
            Map<String, Set<Integer>> transition = transitions.getOrDefault(i, transitions.get(DEAD_STATE));

            // Get all possible transitions for "0" and "1"
            Set<Integer> nextStatesOn0 = transition.getOrDefault("0", Set.of(DEAD_STATE));
            Set<Integer> nextStatesOn1 = transition.getOrDefault("1", Set.of(DEAD_STATE));

            // Convert state numbers to state labels
            String transitionOn0 = nextStatesOn0.stream()
                .map(state -> state == DEAD_STATE ? "qd" : "q" + state)
                .collect(Collectors.joining(", "));

            String transitionOn1 = nextStatesOn1.stream()
                .map(state -> state == DEAD_STATE ? "qd" : "q" + state)
                .collect(Collectors.joining(", "));

            // Add row to the table with formatted state transitions
            model.addRow(new Object[]{
                stateLabels[i],  // State label (e.g., q0, q1, etc.)
                transitionOn0,   // Transitions for symbol "0"
                transitionOn1    // Transitions for symbol "1"
            });
        }
    }




    private void simulateNDFA(JTextArea taOutput, String criteria) {
        inputIndex = 0;
        final Set<Integer>[] currentStates = new Set[]{new HashSet<>()};
        currentStates[0].add(0); // Initial state as a set

        taOutput.setText("Starting NDFA Simulation...\n");
        log(taOutput, "Input String: " + inputString);
        log(taOutput, "Criteria: " + criteria);
        log(taOutput, "Initial States: " + currentStates[0]);

        Timer timer = new Timer(1000, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (inputIndex < inputString.length()) {
                    String symbol = String.valueOf(inputString.charAt(inputIndex));
                    Set<Integer> nextStates = new HashSet<>();
                    for (int state : currentStates[0]) {
                        nextStates.addAll(transitions
                            .getOrDefault(state, transitions.get(DEAD_STATE))
                            .getOrDefault(symbol, Set.of(DEAD_STATE))
                        );
                    }
                    currentStates[0] = nextStates; // Mutable wrapper allows reassignment
                    log(taOutput, "After reading symbol '" + symbol + "': " + currentStates[0]);
                    inputIndex++;
                } else {
                    ((Timer) e.getSource()).stop();
                    finalizeNDFA(currentStates[0], criteria, taOutput);
                }
            }
        });
        timer.start();
    }

    private void finalizeNDFA(Set<Integer> currentStates, String criteria, JTextArea taOutput) {
        boolean accepted = switch (criteria) {
            case "Ends with '11'" -> currentStates.contains(2);
            case "Contains '110'" -> currentStates.contains(3);
            case "Ends with '01'" -> currentStates.contains(2);
            default -> false;
        };

        String result = accepted ? "String Accepted!" : "String Rejected!";
        log(taOutput, result);
        JOptionPane.showMessageDialog(this, result, "Result", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void log(JTextArea taOutput, String message) {
        taOutput.append(message + "\n");
    }
    
    private void designComponents() {
        // Set icon image for the program
        //ImageIcon img = new ImageIcon("src/icon.png");
        //this.setIconImage(img.getImage());
        // Center window when running
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2 - 25);
        this.setLocation(x, y);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NonDeterministicFA_Copy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NonDeterministicFA_Copy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NonDeterministicFA_Copy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NonDeterministicFA_Copy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        FlatLightLaf.registerCustomDefaultsSource("style");
        FlatLightLaf.setup();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NonDeterministicFA_Copy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnValidate;
    private javax.swing.JComboBox<String> cmbCriteria;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCriteria;
    private javax.swing.JLabel lblInput;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblTransitionTable;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea taOutput;
    private javax.swing.JTable tblTransition;
    private javax.swing.JTextField tfInput;
    private javax.swing.JLabel windowBg;
    // End of variables declaration//GEN-END:variables
}
