/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cst4l;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author Mish
 */
public class NonDeterministicFA extends javax.swing.JFrame {

    /**
     * Creates new form pushdownGUI
     */
    public NonDeterministicFA() {
        initComponents();
        designComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lblCriteria = new javax.swing.JLabel();
        cmbCriteria = new javax.swing.JComboBox<>();
        taScrollPane = new javax.swing.JScrollPane();
        taTransition = new javax.swing.JTextArea();
        lblTransitionTable = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblInput = new javax.swing.JLabel();
        tfInput = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnValidate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblOutput = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        windowBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deterministic Finite Automaton");
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCriteria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCriteria.setForeground(new java.awt.Color(66, 168, 166));
        lblCriteria.setText("NFA will accept strings that:");
        lblCriteria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(lblCriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 169, -1));

        cmbCriteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contains '101'", "Second-last digit is '1'" }));
        panel.add(cmbCriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 350, -1));

        taTransition.setEditable(false);
        taTransition.setColumns(20);
        taTransition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taTransition.setRows(2);
        taTransition.setTabSize(1);
        taTransition.setAutoscrolls(false);
        taScrollPane.setViewportView(taTransition);

        panel.add(taScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 350, 100));

        lblTransitionTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTransitionTable.setForeground(new java.awt.Color(66, 168, 166));
        lblTransitionTable.setText("Transition Table:");
        panel.add(lblTransitionTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 182, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FINITE AUTOMATON");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 370, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("---------- NON-DETERMINISTIC -------------");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 370, 30));

        lblInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInput.setForeground(new java.awt.Color(66, 168, 166));
        lblInput.setText("Enter string:");
        panel.add(lblInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 221, -1));
        panel.add(tfInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 350, -1));

        btnClear.setBackground(new java.awt.Color(97, 193, 191));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        panel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 90, 30));

        btnValidate.setBackground(new java.awt.Color(97, 193, 191));
        btnValidate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnValidate.setForeground(new java.awt.Color(255, 255, 255));
        btnValidate.setText("Validate");
        btnValidate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateActionPerformed(evt);
            }
        });
        panel.add(btnValidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 350, 30));

        btnBack.setBackground(new java.awt.Color(97, 193, 191));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        btnBack.setText(" Back");
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        panel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        btnExit.setBackground(new java.awt.Color(97, 193, 191));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 90, 30));

        lblOutput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOutput.setForeground(new java.awt.Color(66, 168, 166));
        lblOutput.setText("Output");
        panel.add(lblOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 182, -1));

        taOutput.setEditable(false);
        taOutput.setColumns(20);
        taOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taOutput.setRows(1);
        taOutput.setTabSize(1);
        taOutput.setAutoscrolls(false);
        jScrollPane2.setViewportView(taOutput);

        panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 350, 30));

        windowBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bgNDFA.png"))); // NOI18N
        panel.add(windowBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tfInput.setText("");
        taOutput.setText("");
        taTransition.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new MainDashboard().setVisible(true); 
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateActionPerformed
        String inputString = tfInput.getText();
        
        if (!inputString.matches("[01]+")){
            JOptionPane.showMessageDialog(this, "Input must be binary numbers (0 or 1 only).", 
                    "Invalid Input", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean accepted = simulateNDFA(inputString);
            initializeTransitionTable();
            if (accepted) {
                taOutput.setText("String accepted.");
            } else {
                taOutput.setText("String rejected.");
            }
        }
    }//GEN-LAST:event_btnValidateActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Exit program?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed
    
    private void initializeTransitionTable() {
        String criteria = (String) cmbCriteria.getSelectedItem();
        String transition = "";
        if (criteria.equalsIgnoreCase("Contains '101'")){
            transition += "States \t\tInput 0 \t\tInput 1\n";
            transition += "q0 \t\t\t\tq0 \t\t\t\tq0,q1\n";
            transition += "q1 \t\t\t\tq2 \t\t\t\tq2\n";
            transition += "q2 \t\t\t\tq2 \t\t\t\tq2\n";
        }
        if (criteria.equalsIgnoreCase("Second-last digit is '1'")){
            transition += "States \t\tInput 0 \t\tInput 1\n";
            transition += "q0 \t\t\t\tq0 \t\t\t\tq0,q1\n";
            transition += "q1 \t\t\t\tq2 \t\t\t\tq2\n";
            transition += "q2 \t\t\t\t-- \t\t\t\t--\n";
        }
        taTransition.setText(transition);
    }
    
    private boolean simulateNDFA(String input){
        String criteria = (String) cmbCriteria.getSelectedItem();
        boolean accepted = true;
        if (criteria.equalsIgnoreCase("Contains '101'")){
            accepted = simulateNDFA1(input);
        } else if (criteria.equalsIgnoreCase("Second-last digit is '1'")){
            accepted = simulateNDFA2(input);
        }
        return accepted;
    }

    private boolean simulateNDFA1(String input) {
        Set<String> currentStates = new HashSet<>();
        currentStates.add("q0");

        for (char symbol : input.toCharArray()) {
            Set<String> nextStates = new HashSet<>();
            for (String state : currentStates) {
                switch (state) {
                    case "q0":
                        if (symbol == '0') {
                            nextStates.add("q0");
                        } else if (symbol == '1') {
                            nextStates.add("q0");
                            nextStates.add("q1");
                        }
                        break;
                    case "q1":
                        if (symbol == '0') {
                            nextStates.add("q2");
                        }
                        break;
                    case "q2":
                        if (symbol == '1') {
                            nextStates.add("q2"); // Stay in q2 if the next symbol is 1
                        }
                        break;
                }
            }
            currentStates = nextStates;
        }

        return currentStates.contains("q2"); // Accept if we reach q2 after processing the entire input
    }
    
    private boolean simulateNDFA2(String input) {
        Set<String> currentStates = new HashSet<>();
        currentStates.add("q0");

        for (int i = 0; i < input.length(); i++) {
            char symbol = input.charAt(i);
            Set<String> nextStates = new HashSet<>();
            for (String state : currentStates) {
                switch (state) {
                    case "q0":
                        if (symbol == '0') {
                            nextStates.add("q0");
                        } else if (symbol == '1') {
                            nextStates.add("q0");
                            nextStates.add("q1");
                        }
                        break;
                    case "q1":
                        if (i == input.length() - 2) { // Second-to-last character
                            if (symbol == '1') {
                                nextStates.add("q2"); // Transition to q2 only if the second-to-last character is 1
                            }
                        } else {
                            nextStates.add("q1"); // Stay in q1 if not the second-to-last character
                        }
                        break;
                    case "q2":
                        nextStates.add("q2"); // Stay in q2 after reaching it
                        break;
                }
            }
            currentStates = nextStates;
        }

        return currentStates.contains("q2"); // Accept if we reach q2 after processing the entire input
    }
    
    private void designComponents() {
        // Set icon image for the program
        //ImageIcon img = new ImageIcon("src/icon.png");
        //this.setIconImage(img.getImage());
        // Center window when running
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2 - 25);
        this.setLocation(x, y);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NonDeterministicFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NonDeterministicFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NonDeterministicFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NonDeterministicFA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        FlatLightLaf.registerCustomDefaultsSource("style");
        FlatLightLaf.setup();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.print("Table updated");
                new NonDeterministicFA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnValidate;
    private javax.swing.JComboBox<String> cmbCriteria;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCriteria;
    private javax.swing.JLabel lblInput;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblTransitionTable;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea taOutput;
    private javax.swing.JScrollPane taScrollPane;
    private javax.swing.JTextArea taTransition;
    private javax.swing.JTextField tfInput;
    private javax.swing.JLabel windowBg;
    // End of variables declaration//GEN-END:variables
}
