/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cst4l;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author Mish
 */
public class PushdownAutomata extends javax.swing.JFrame {

    /**
     * Creates new form pushdownGUI
     */
    public PushdownAutomata() {
        initComponents();
        designComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textFieldN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldString = new javax.swing.JTextField();
        buttonClear = new javax.swing.JButton();
        buttonTest = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaOutput = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        lblTransition = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaResult = new javax.swing.JTextArea();
        windowBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pushdown Automata");
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pushdown Automata");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 20, 390, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(88, 130, 105));
        jLabel1.setText("Enter the value of n:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 169, -1));

        textFieldN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNActionPerformed(evt);
            }
        });
        panel.add(textFieldN, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 360, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(88, 130, 105));
        jLabel2.setText("Enter a string to be tested:");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 221, -1));

        textFieldString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldStringActionPerformed(evt);
            }
        });
        panel.add(textFieldString, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 360, -1));

        buttonClear.setBackground(new java.awt.Color(77, 166, 113));
        buttonClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonClear.setForeground(new java.awt.Color(255, 255, 255));
        buttonClear.setText("Clear");
        buttonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        panel.add(buttonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 90, 30));

        buttonTest.setBackground(new java.awt.Color(77, 166, 113));
        buttonTest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonTest.setForeground(new java.awt.Color(255, 255, 255));
        buttonTest.setText("Test");
        buttonTest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTestActionPerformed(evt);
            }
        });
        panel.add(buttonTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 180, 30));
        panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 320, 10));

        textAreaOutput.setEditable(false);
        textAreaOutput.setColumns(20);
        textAreaOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textAreaOutput.setRows(5);
        textAreaOutput.setAutoscrolls(false);
        jScrollPane1.setViewportView(textAreaOutput);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 360, 80));

        btnBack.setBackground(new java.awt.Color(77, 166, 113));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        btnBack.setText(" Back");
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        panel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        buttonExit.setBackground(new java.awt.Color(77, 166, 113));
        buttonExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonExit.setForeground(new java.awt.Color(255, 255, 255));
        buttonExit.setText("Exit");
        buttonExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        panel.add(buttonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 90, 30));

        lblTransition.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTransition.setForeground(new java.awt.Color(88, 130, 105));
        lblTransition.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTransition.setText("Transition");
        panel.add(lblTransition, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 244, -1));

        lblResult.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResult.setForeground(new java.awt.Color(88, 130, 105));
        lblResult.setText("Result");
        panel.add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 182, -1));

        textAreaResult.setEditable(false);
        textAreaResult.setColumns(20);
        textAreaResult.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textAreaResult.setRows(2);
        textAreaResult.setAutoscrolls(false);
        jScrollPane2.setViewportView(textAreaResult);

        panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 360, 80));

        windowBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bgPDA.png"))); // NOI18N
        windowBg.setText("jLabel4");
        panel.add(windowBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // TODO add your handling code here:
        // Clear input fields and text area
        textFieldN.setText("");
        textFieldString.setText("");
        textAreaOutput.setText("");
        textAreaResult.setText("");
    }//GEN-LAST:event_buttonClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new MainDashboard().setVisible(true); 
    }//GEN-LAST:event_btnBackActionPerformed

    private void buttonTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTestActionPerformed
        // TODO add your handling code here:
        textAreaOutput.append("---------------------------------\n");
        handleTestAction();
    }//GEN-LAST:event_buttonTestActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Exit program?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_buttonExitActionPerformed

    private void textFieldNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNActionPerformed

    private void textFieldStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldStringActionPerformed
    
    private void handleTestAction() {
        try {
            int n = Integer.parseInt(textFieldN.getText());
            String inputString = textFieldString.getText();

            // Count occurrences of 'a' and 'b'
            long countA = inputString.chars().filter(c -> c == 'a').count();
            long countB = inputString.chars().filter(c -> c == 'b').count();

            textAreaOutput.append("For n: " + n + ", string: " + inputString + "\n");

            // Run transitions for any string
            boolean stackEmpty = simulatePDA(inputString, n);

            if (countA == countB) {
                if (countA == n) {
                    // Matches a^n b^n for the input n
                    if (stackEmpty) {
                        textAreaResult.append("For n: " + n + ", string: " + inputString + "\n");
                        textAreaResult.append("Accepted: The string follows a^n b^n.\n");
                        textAreaResult.append("------------------------------------------------------\n");

                    } else {
                        textAreaResult.append("For n: " + n + ", string: " + inputString + "\n");
                        textAreaResult.append("Rejected: Input invalid.\n");
                        textAreaResult.append("------------------------------------------------------\n");
                    }
                } else {
                    // Matches a^m b^m but not n
                    textAreaResult.append("For n: " + n + ", string: " + inputString + "\n");
                    textAreaResult.append("Rejected: Although the string contains equal\n");
                    textAreaResult.append("occurrences of 'a' and 'b', it does not match the\n");
                    textAreaResult.append("specified value of n.\n");
                    textAreaResult.append("------------------------------------------------------\n");
                }
            } else {
                // Cases with mismatched countA and countB
                textAreaResult.append("For n: " + n + ", string: " + inputString + "\n");
                textAreaResult.append("Rejected: The string does not follow a^n b^n.\n");
                textAreaResult.append("------------------------------------------------------\n");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Please enter a valid integer for n.");
        }
    }

    public boolean simulatePDA(String input, int n) {
        Stack<Character> stack = new Stack<>();
        int state = 0; // Initial state q0
        String remainingInput = input;

        // Always display initial PDA step
        textAreaOutput.append("δ: (q0, " + remainingInput + ", " + stackToString(stack) + ")\n");

        // Process the input string character by character
        for (char symbol : input.toCharArray()) {
            switch (state) {
                case 0:
                    if (symbol == 'a') {
                        stack.push('a');
                        remainingInput = remainingInput.substring(1);
                        if (!remainingInput.isEmpty()) {
                            textAreaOutput.append("δ: (q0, " + remainingInput + ", " + stackToString(stack) + ")\n");
                        }
                    } else if (symbol == 'b' && !stack.isEmpty()) {
                        state = 1;
                        textAreaOutput.append("δ: (q1, " + remainingInput + ", " + stackToString(stack) + ")\n");
                        stack.pop();
                        remainingInput = remainingInput.substring(1);
                    } else {
                        // Invalid transition: the string has more 'b's before 'a's are matched
                        return false;
                    }
                    break;

                case 1:
                    if (symbol == 'b' && !stack.isEmpty()) {
                        textAreaOutput.append("δ: (q1, " + remainingInput + ", " + stackToString(stack) + ")\n");
                        stack.pop();
                        remainingInput = remainingInput.substring(1);
                    } else {
                        // Invalid transition: the string has 'a' after 'b' state, or stack is empty when trying to pop
                        return false;
                    }
                    break;

                default:
                    return false;
            }
        }

        // Final steps based on the state and stack
        if (remainingInput.isEmpty() && state == 0) {
            textAreaOutput.append("δ: (q0, ε, " + stackToString(stack) + ")\n");
        } else if (remainingInput.isEmpty()) {
            textAreaOutput.append("δ: (q1, ε, " + stackToString(stack) + ")\n");
        }

        if (stack.isEmpty() && state == 1) {
            textAreaOutput.append("δ: (qf, ε, [])\n");
            return true; // Accept
        }

        return false; // Reject
    }

    public String stackToString(Stack<Character> stack) {
        if (stack.isEmpty()) {
            return "[]";
        }
        StringBuilder stackString = new StringBuilder("[");
        for (Character c : stack) {
            stackString.append(c).append(", ");
        }
        stackString.setLength(stackString.length() - 2);
        stackString.append("]");
        return stackString.toString();
    }
    
    private void designComponents() {
        // Set icon image for the program
        //ImageIcon img = new ImageIcon("src/icon.png");
        //this.setIconImage(img.getImage());
        // Center window when running
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2 - 25);
        this.setLocation(x, y);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PushdownAutomata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PushdownAutomata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PushdownAutomata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PushdownAutomata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        FlatLightLaf.registerCustomDefaultsSource("style");
        FlatLightLaf.setup();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PushdownAutomata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTransition;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea textAreaOutput;
    private javax.swing.JTextArea textAreaResult;
    private javax.swing.JTextField textFieldN;
    private javax.swing.JTextField textFieldString;
    private javax.swing.JLabel windowBg;
    // End of variables declaration//GEN-END:variables
}
