/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cst4l;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Mish
 */
public class TowerOfHanoi extends javax.swing.JFrame {

    /**
     * Creates new form pushdownGUI
     */
    public TowerOfHanoi() {
        initComponents();
        designComponents();
        TowerOfHanoiGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taStates = new javax.swing.JTextArea();
        tfSteps = new javax.swing.JTextField();
        lblSteps = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        tfInput = new javax.swing.JTextField();
        lblInput = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        windowBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pushdown Automata");
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("--------------- SIMULATION ------------------");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 440, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 730, 370));

        taStates.setEditable(false);
        taStates.setBackground(new java.awt.Color(255, 255, 255));
        taStates.setColumns(20);
        taStates.setRows(2);
        taStates.setTabSize(1);
        jScrollPane1.setViewportView(taStates);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 220, 370));

        tfSteps.setEnabled(false);
        tfSteps.setFocusable(false);
        tfSteps.setRequestFocusEnabled(false);
        panel.add(tfSteps, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 60, 30));

        lblSteps.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSteps.setForeground(new java.awt.Color(165, 54, 91));
        lblSteps.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSteps.setText("Steps: ");
        lblSteps.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(lblSteps, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 80, 30));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("TOWER OF HANOI");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 400, 60));

        tfInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputActionPerformed(evt);
            }
        });
        panel.add(tfInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 120, 30));

        lblInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInput.setForeground(new java.awt.Color(165, 54, 91));
        lblInput.setText("Enter n (number of discs):");
        lblInput.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(lblInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 150, 30));

        btnReset.setBackground(new java.awt.Color(184, 71, 105));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        panel.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 100, 30));

        btnStart.setBackground(new java.awt.Color(184, 71, 105));
        btnStart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("Start");
        btnStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        panel.add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 100, 30));

        btnBack.setBackground(new java.awt.Color(184, 71, 105));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        btnBack.setText(" Back");
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        panel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        btnExit.setBackground(new java.awt.Color(184, 71, 105));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, 90, 30));

        windowBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bgTOH.png"))); // NOI18N
        windowBg.setText("jLabel4");
        panel.add(windowBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        // Clear input fields and text area
        tfInput.setText("");
        tfSteps.setText("");
        resetGame();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new MainDashboard().setVisible(true); 
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        String input = tfInput.getText().trim(); // Get and trim the input text
        try {
            int number = Integer.parseInt(input); // Try parsing the input to an integer

            // Validate the input range
            if (number < 1 || number > 7) {
                JOptionPane.showMessageDialog(this, 
                    "Please input only numbers from 1-7.", 
                    "Invalid Range", 
                    JOptionPane.ERROR_MESSAGE);
            } else {
                startGame(); // Proceed to start the game
            }
        } catch (NumberFormatException ex) {
            // Show an error message if the input is not a valid number
            JOptionPane.showMessageDialog(this, 
                "Input must be a valid number.", 
                "Invalid Input", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Exit program?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void tfInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputActionPerformed
   
    private void designComponents() {
        // Set icon image for the program
        //ImageIcon img = new ImageIcon("src/icon.png");
        //this.setIconImage(img.getImage());
        // Center window when running
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2 - 25);
        this.setLocation(x, y);
    }
    
    public TowerPanel towerPanel;
    public Stack<Integer> poleA, poleB, poleC;
    public int[] moveCount;
    public int diskCount;
    public Timer moveTimer;
    public String[] moveSteps;
    public int currentStep;
    
    public void TowerOfHanoiGUI() {
        // Initialize the stacks and move count
        towerPanel = new TowerPanel();
        panel.add(towerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 730, 375)); // Adjust constraints as needed
        poleA = new Stack<>();
        poleB = new Stack<>();
        poleC = new Stack<>();
        moveCount = new int[1];
        
        // Timer for animation effect
        moveTimer = new Timer(1500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                moveStep();
            }
        });
    }

    private void startGame() {
        try {
            diskCount = Integer.parseInt(tfInput.getText());
            if (diskCount < 1) {
                JOptionPane.showMessageDialog(this, "Please enter a valid number of disks.");
                return;
            }
            poleA.clear();
            poleB.clear();
            poleC.clear();
            moveCount[0] = 0;
            currentStep = 0;

            // Initialize pole A with disks (largest disks at the bottom)
            for (int i = diskCount; i >= 1; i--) {
                poleA.push(i);
            }

            // Display initial state
            taStates.setText("Initial State:\n");  // Clear the text area
            printTowerState();     // Print the initial tower state
            tfSteps.setText("0");  // Reset the steps label

            towerPanel.repaint();  // Redraw the initial state

            // Dynamically allocate space for move steps
            moveSteps = new String[(int) Math.pow(2, diskCount) - 1];

            // Solve Tower of Hanoi
            towerOfHanoi(diskCount, "A", "C", "B", poleA, poleC, poleB);

            moveTimer.start(); // Start the timer to animate the solution
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a number.");
        }
    }

    // Recursive method to solve Tower of Hanoi with step-by-step moves
    private void towerOfHanoi(int n, String source, String target, String auxiliary, 
                              Stack<Integer> sourceStack, Stack<Integer> targetStack, 
                              Stack<Integer> auxiliaryStack) {
        if (n == 1) {
            moveSteps[moveCount[0]] = "Move disk 1 from " + source + " to " + target;
            moveCount[0]++;
            return;
        }
        towerOfHanoi(n - 1, source, auxiliary, target, sourceStack, auxiliaryStack, targetStack);
        moveSteps[moveCount[0]] = "Move disk " + n + " from " + source + " to " + target;
        moveCount[0]++;
        towerOfHanoi(n - 1, auxiliary, target, source, auxiliaryStack, targetStack, sourceStack);
    }

    // Method to print the tower state to the text area
    private void printTowerState() {
        StringBuilder sb = new StringBuilder();
        sb.append("Pole A: ").append(poleA.isEmpty() ? "Empty" : poleA).append("\n");
        sb.append("Pole B: ").append(poleB.isEmpty() ? "Empty" : poleB).append("\n");
        sb.append("Pole C: ").append(poleC.isEmpty() ? "Empty" : poleC).append("\n");
        sb.append("\n");
        taStates.append(sb.toString());
    }


    // Method to move a disk from one pole to another
    private void moveDisk(String fromPole, String toPole, Stack<Integer> fromStack, Stack<Integer> toStack) {
        int disk = fromStack.pop();
        toStack.push(disk);
        printTowerState();
        towerPanel.repaint();  // Redraw the tower with updated state
    }

    // Method to perform one step of the Tower of Hanoi moves
    private void moveStep() {
        if (currentStep < moveCount[0]) {
            // Process the current move step
            String moveDescription = moveSteps[currentStep];
            taStates.append(moveDescription + "\n");

            // Parse the move description to extract the disk and poles
            String[] parts = moveDescription.split(" ");
            int disk = Integer.parseInt(parts[2]);
            String fromPole = parts[4];
            String toPole = parts[6];

            Stack<Integer> fromStack = getPoleStack(fromPole);
            Stack<Integer> toStack = getPoleStack(toPole);

            moveDisk(fromPole, toPole, fromStack, toStack);

            currentStep++;

            // Update the steps label
            tfSteps.setText(String.valueOf(currentStep));
        } else {
            moveTimer.stop();  // Stop after completing all moves
            taStates.append("\nTotal moves: " + moveCount[0]);
        }
    }

    // Helper method to get the stack for a given pole
    private Stack<Integer> getPoleStack(String pole) {
        switch (pole) {
            case "A":
                return poleA;
            case "B":
                return poleB;
            case "C":
                return poleC;
            default:
                return null;
        }
    }

    // Method to reset the game and clear everything
    private void resetGame() {
        tfInput.setText("");
        taStates.setText("");
        moveCount[0] = 0;
        poleA.clear();
        poleB.clear();
        poleC.clear();
        towerPanel.repaint();
        tfSteps.setText("0");  // Reset the steps label
    }

    private class TowerPanel extends JPanel {
        private static final long serialVersionUID = 1L;

        // Draw the components: poles and disks
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);

            int panelWidth = getWidth();
            int panelHeight = getHeight();

            int poleWidth = 20;
            int poleHeight = panelHeight - 50;
            int baseHeight = 20;

            // Space between poles and boundaries
            int margin = 30;

            // Number of spaces to divide the width (3 poles and 4 margins)
            int totalDivisions = 6;

            int spaceBetweenPoles = (panelWidth - 2 * margin) / totalDivisions;
            int pole1X = margin + spaceBetweenPoles;
            int pole2X = pole1X + 2 * spaceBetweenPoles;
            int pole3X = pole2X + 2 * spaceBetweenPoles;

            // Draw poles
            drawPole(g, pole1X, poleHeight);
            drawPole(g, pole2X, poleHeight);
            drawPole(g, pole3X, poleHeight);

            // Draw disks on each pole
            drawTower(g, poleA, pole1X);
            drawTower(g, poleB, pole2X);
            drawTower(g, poleC, pole3X);
        }

        // Method to draw the pole (fixed height and dynamic X position)
        private void drawPole(Graphics g, int x, int height) {
            g.setColor(Color.LIGHT_GRAY);
            int poleBottom = getHeight(); // Keep some space for base
            g.fillRect(x - 5, poleBottom - height, 10, height); // Centered at x
        }

        // Method to draw the disks with pastel colors
        private void drawTower(Graphics g, Stack<Integer> pole, int x) {
            int y = getHeight() - 20;
            int diskHeight = 20;
            int poleBottom = getHeight();
            int maxDiskWidth = getWidth() / 4;

            for (int i = 0; i < pole.size(); i++) {
                int disk = pole.get(i);

                g.setColor(new Color(100 + disk * 20, 150, 200));
                g.fillRect(x - disk * 15, y - i * 20, disk * 30, 20);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TowerOfHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TowerOfHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TowerOfHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TowerOfHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        FlatLightLaf.registerCustomDefaultsSource("style");
        FlatLightLaf.setup();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TowerOfHanoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInput;
    private javax.swing.JLabel lblSteps;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea taStates;
    private javax.swing.JTextField tfInput;
    private javax.swing.JTextField tfSteps;
    private javax.swing.JLabel windowBg;
    // End of variables declaration//GEN-END:variables
}
