package cst4l;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class TuringMachine extends javax.swing.JFrame {

    /**
     * Creates new form TuringMachine
     */
    public TuringMachine() {
        initComponents();
        designComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        taResult = new javax.swing.JTextArea();
        lblResult = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taFinalTape = new javax.swing.JTextArea();
        lblFinalTape = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taInitialTape = new javax.swing.JTextArea();
        lblInitialTape = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        cmbOperation = new javax.swing.JComboBox<>();
        lblOperation = new javax.swing.JLabel();
        tfSecondNum = new javax.swing.JTextField();
        lblSecondNum = new javax.swing.JLabel();
        tfFirstNum = new javax.swing.JTextField();
        lblFirstNum = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        windowBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Turing Machine Operations");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(150, 97, 193));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        btnBack.setText(" Back");
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        taResult.setEditable(false);
        taResult.setBackground(new java.awt.Color(255, 255, 255));
        taResult.setColumns(20);
        taResult.setForeground(new java.awt.Color(51, 51, 51));
        taResult.setLineWrap(true);
        taResult.setRows(3);
        taResult.setTabSize(3);
        taResult.setWrapStyleWord(true);
        taResult.setFocusable(false);
        jScrollPane3.setViewportView(taResult);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 420, 60));

        lblResult.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResult.setForeground(new java.awt.Color(108, 45, 158));
        lblResult.setText("Result:");
        jPanel1.add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 140, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        taFinalTape.setEditable(false);
        taFinalTape.setBackground(new java.awt.Color(255, 255, 255));
        taFinalTape.setColumns(20);
        taFinalTape.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        taFinalTape.setForeground(new java.awt.Color(51, 51, 51));
        taFinalTape.setRows(1);
        taFinalTape.setWrapStyleWord(true);
        taFinalTape.setFocusable(false);
        jScrollPane2.setViewportView(taFinalTape);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 420, 30));

        lblFinalTape.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFinalTape.setForeground(new java.awt.Color(108, 45, 158));
        lblFinalTape.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinalTape.setText("Final Input Tape");
        jPanel1.add(lblFinalTape, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 150, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        taInitialTape.setEditable(false);
        taInitialTape.setBackground(new java.awt.Color(255, 255, 255));
        taInitialTape.setColumns(20);
        taInitialTape.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        taInitialTape.setForeground(new java.awt.Color(51, 51, 51));
        taInitialTape.setRows(1);
        taInitialTape.setWrapStyleWord(true);
        taInitialTape.setFocusable(false);
        jScrollPane1.setViewportView(taInitialTape);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 420, 30));

        lblInitialTape.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInitialTape.setForeground(new java.awt.Color(108, 45, 158));
        lblInitialTape.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInitialTape.setText("Initial Input Tape");
        jPanel1.add(lblInitialTape, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 150, -1));

        btnClear.setBackground(new java.awt.Color(150, 97, 193));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 120, 30));

        btnExit.setBackground(new java.awt.Color(150, 97, 193));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 120, 30));

        btnCalculate.setBackground(new java.awt.Color(150, 97, 193));
        btnCalculate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("Calculate");
        btnCalculate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 160, 30));

        cmbOperation.setForeground(new java.awt.Color(51, 51, 51));
        cmbOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "*" }));
        cmbOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOperationActionPerformed(evt);
            }
        });
        jPanel1.add(cmbOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 250, 60, -1));

        lblOperation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOperation.setForeground(new java.awt.Color(108, 45, 158));
        lblOperation.setText("Operation");
        jPanel1.add(lblOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 60, -1));

        tfSecondNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        tfSecondNum.setForeground(new java.awt.Color(51, 51, 51));
        tfSecondNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSecondNumActionPerformed(evt);
            }
        });
        jPanel1.add(tfSecondNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 160, -1));

        lblSecondNum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSecondNum.setForeground(new java.awt.Color(108, 45, 158));
        lblSecondNum.setText("Second Number (in binary):");
        jPanel1.add(lblSecondNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 160, -1));

        tfFirstNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        tfFirstNum.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(tfFirstNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 160, -1));

        lblFirstNum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFirstNum.setForeground(new java.awt.Color(108, 45, 158));
        lblFirstNum.setText("First Number (in binary):");
        jPanel1.add(lblFirstNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 160, -1));

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("OPERATIONS");
        jPanel1.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 450, 60));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("-------- TURING MACHINE --------");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 450, 30));

        windowBg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        windowBg.setForeground(new java.awt.Color(51, 51, 51));
        windowBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bgTM.png"))); // NOI18N
        jPanel1.add(windowBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        String num1 = tfFirstNum.getText().trim();
        String num2 = tfSecondNum.getText().trim();
        String operation = cmbOperation.getSelectedItem().toString();
        if (tfFirstNum.getText().isEmpty() || tfSecondNum.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill out all fields.",
                    "Incomplete Equation", JOptionPane.ERROR_MESSAGE);
        } else if (!isBinary(num1) || !isBinary(num2)) {
            JOptionPane.showMessageDialog(this, "Inputs must be binary numbers (0 or 1 only).",
                    "Invalid Input", JOptionPane.ERROR_MESSAGE);
        } else {        
            switch (operation) {
                case "+":
                    if (!isBinary(num1) || !isBinary(num2)) {
                        JOptionPane.showMessageDialog(this, "Inputs must be binary numbers (0 or 1 only).", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                    } else {
                        // Ensure both numbers have the same length by padding with zeros
                        int maxLength = Math.max(num1.length(), num2.length());
                        num1 = padLeftZeros(num1, maxLength);
                        num2 = padLeftZeros(num2, maxLength);

                        System.out.println("---Addition Operation---\n");
                        addBinaryNumbers(num1, num2);
                    }
                    break;
                case "*":
                    if (!isUnary(num1) || !isUnary(num2)) {
                        JOptionPane.showMessageDialog(this, "Inputs must be unary numbers (1 only).", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                    } else {
                        System.out.println("---Multiplication Operation---\n");
                        multiplyBinaryNumbers(num1, num2);
                    }
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Please double-check all text fields.",
                            "Incomplete Equation", JOptionPane.ERROR_MESSAGE);
                    break;
            }
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private String addBinaryNumbers(String num1, String num2) {
        String equation = "B" + num1 + "+" + num2 + "B";
        char[] tape = equation.toCharArray();
        int head = 1;  
        String state = "q0"; 
        String direction ="R";
        int countSteps = 0;
        
        //Get decimal numbers of the binary numbers
        int decimalNum1 = Integer.parseInt(num1, 2);
        int decimalNum2 = Integer.parseInt(num2, 2);

        //Set Initial Tape
        String initialTapeDiagram = getInputTape(equation);
        taInitialTape.setText(initialTapeDiagram);
        
        System.out.println("Inputs: " + num1 + " " + "+" + " " + num2);
        System.out.println("Inputs in decimals: " + decimalNum1 + " " + "+" + " " + decimalNum2 + "\n");
      
        while (true) {
            char currentSymbol = tape[head]; 
            System.out.println("Tape: " + new String(tape));
            System.out.print("Î´("+ state + ", " + currentSymbol  + ")");
            
            switch (state) {
                case "q0": 
                    if (currentSymbol == 'B') {
                    	state = "q1"; 
                        head--;
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                        
                    } else {
                        head++;
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break;

                case "q1": 
                    if (currentSymbol == '0') {
                        tape[head] = '1'; 
                        head--; 
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", 1, " + direction + ")");
                    } else if (currentSymbol == '1') {
                        tape[head] = '0'; 
                        state = "q2";
                        head--; 
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", 0, " + direction + ")");
                    } else if (currentSymbol == '+') {
                        tape[head] = 'B';                        
                        state = "q4"; 
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", B, " + direction + ")");
                    } else {
                        head--; 
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break;

                case "q2": 
                    if (currentSymbol == '+') {                       
                        state = "q3"; 
                        head--; 
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    } else {
                        head--; 
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break;
                    
                case "q3": 
                    if (currentSymbol == '0') {
                        tape[head] = '1';                        
                        state = "q0"; 
                        head++;
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", 1, " + direction + ")");
                    } else if (currentSymbol == '1') {
                        tape[head] = '0'; 
                        head--; 
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", 0, " + direction + ")");
                    } else if (currentSymbol == 'B') {
                        tape[head] = '1'; 
                        head++; 
                        state = "q0"; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", 1, " + direction + ")");
                    } else {
                        head--; 
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break;
                    
                case "q4": 
                    if (currentSymbol == '1') {
                        tape[head] = 'B';
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", B, " + direction + ")");
                    } else if (currentSymbol == 'B') {
                        state = "q5";
                        System.out.println(" -> Î´("+ state + ", " + "HALT"  + ")");
                    } else {
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break;  
            }
            if (state.equals("q5")) {
                break;
            }
            countSteps++;
        }
        //Final State
        String finalTape = new String(tape);
        System.out.println("Final Tape: " + finalTape);
        
        String finalTapeDiagram = getInputTape(finalTape);
        taFinalTape.setText(finalTapeDiagram);
        
        StringBuilder binarySum = new StringBuilder();
        for (char c : tape) {
            if (c == '0' || c == '1') {
                binarySum.append(c);
            }
        }
        String resultText = "";
        int sum = Integer.parseInt(binarySum.toString(), 2);
        
        //Print results in console
        System.out.println("Equation: "+num1+"["+decimalNum1+"] + "+num2+"["+decimalNum2+"] = "+binarySum+"["+sum+"]");
        System.out.println("Addition Result in Decimal: " + sum);
        System.out.println("Addition Result in Binary: " + binarySum.toString());
        System.out.println("Steps: "+ countSteps + "\n");
        
        //Show results in GUI
        resultText += "Equation: "+num1+"["+decimalNum1+"] + "+num2+"["+decimalNum2+"] = "+binarySum+"["+sum+"]\n";
        resultText += "Addition Result in Decimal: " + sum + "\n";
        resultText += "Addition Result in Binary: " + binarySum.toString() + "\n";
        resultText += "Steps: "+ countSteps + "\n";
        taResult.setText(resultText);
        
        return null;
    }
    
    private String multiplyBinaryNumbers(String num1, String num2) {
        String equation = "B" + num1 + "0" + num2 + "B";
        char[] tape = equation.toCharArray();
        int head = 1;  
        String state = "q0"; 
        String direction ="R";
        int countSteps = 0;
        
        //Get decimal numbers of the unary numbers
        int decimalNum1 = getDecimalOfUnary(num1);
        int decimalNum2 = getDecimalOfUnary(num2);
        
        //Set Initial Tape
        String initialTapeDiagram = getInputTape(equation);
        taInitialTape.setText(initialTapeDiagram);
        
        System.out.println("Inputs: " + num1 + " " + "*" + " " + num2);
        System.out.println("Inputs in decimals: " + decimalNum1 + " " + "*" + " " + decimalNum2 + "\n");
      
        while (true) {
            char currentSymbol = tape[head]; 
            System.out.println("Tape: " + new String(tape));
            System.out.print("Î´("+ state + ", " + currentSymbol  + ")");
            
            switch (state) {
                case "q0": 
                    if (currentSymbol == 'B') {
                        tape[head] = '0'; 
                    	state = "q1"; 
                        head--;
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", 0, " + direction + ")");
                    } else {
                        head++;
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break;

                case "q1": 
                    if (currentSymbol == 'B') {
                        tape[head] = 'B'; 
                        state = "q2";
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", B, " + direction + ")");
                    } else {
                        head--; 
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break;

                case "q2": 
                    if (currentSymbol == '1') { 
                        tape[head] = 'X';
                        state = "q3"; 
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", X, " + direction + ")");
                    } else if (currentSymbol == '0') { 
                        tape[head] = '0';
                        state = "q9"; 
                        head--; 
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", 0, " + direction + ")");
                    } else {
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break;
                    
                case "q3": 
                    if (currentSymbol == '0') {
                        tape[head] = '0';                        
                        state = "q4"; 
                        head++;
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", 0, " + direction + ")");
                    } else if (currentSymbol == '1') {
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    } else {
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break;
                    
                case "q4": 
                    if (currentSymbol == '1') {
                        tape[head] = 'Y';
                        state = "q5";
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", Y, " + direction + ")");
                    } else if (currentSymbol == '0') {
                        tape[head] = '0';
                        state = "q8";
                        head--; 
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", 0, " + direction + ")");
                    } else {
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break;  
                    
                case "q5": 
                    if (currentSymbol == '0') {
                        tape[head] = '0';
                        state = "q6";
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", 0, " + direction + ")");
                    } else if (currentSymbol == '1') {
                        head++;
                        direction = "R";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    } else {
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break; 
                    
                case "q6": 
                    if (currentSymbol == 'B') {
                        tape[head] = '1';
                        state = "q7";
                        head--; 
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", 1, " + direction + ")");
                    } else {
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break;
                    
                case "q7": 
                    if (currentSymbol == 'Y') {
                        tape[head] = 'Y';
                        state = "q4";
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", Y, " + direction + ")");
                    } else if (currentSymbol == '0' || currentSymbol == '1') {
                        head--;
                        direction = "L";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    } else {
                        head--; 
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break;  
                    
                case "q8": 
                    if (currentSymbol == 'X') {
                        tape[head] = 'X';
                        state = "q2";
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", X, " + direction + ")");
                    } else if (currentSymbol == 'Y') {
                        tape[head] = '1';
                        head--;
                        direction = "L";
                        System.out.println(" -> Î´("+ state + ", 1, " + direction + ")");
                    } else {
                        head--; 
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break;  
                    
                case "q9": 
                    if (currentSymbol == 'B') {
                        tape[head] = 'B';
                        state = "q10";
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", X, " + direction + ")");
                    } else if (currentSymbol == 'X') {
                        tape[head] = 'X';
                        head--;
                        direction = "L";
                        System.out.println(" -> Î´("+ state + ", X, " + direction + ")");
                    } else {
                        head--; 
                        direction ="L";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break; 
                    
                case "q10": 
                    if (currentSymbol == '0') {
                        tape[head] = 'B';
                        state = "q11";
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", B, " + direction + ")");
                    } else if (currentSymbol == 'X') {
                        tape[head] = 'B';
                        head++;
                        direction = "R";
                        System.out.println(" -> Î´("+ state + ", B, " + direction + ")");
                    } else {
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break;
                    
                case "q11": 
                    if (currentSymbol == '0') {
                        tape[head] = 'B';
                        state = "q12";
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", B, " + direction + ")");
                    } else if (currentSymbol == '1') {
                        tape[head] = 'B';
                        head++;
                        direction = "R";
                        System.out.println(" -> Î´("+ state + ", B, " + direction + ")");
                    } else {
                        head++; 
                        direction ="R";
                        System.out.println(" -> Î´("+ state + ", " + currentSymbol  + ", " + direction + ")");
                    }
                    System.out.println("");
                    break;
            }
            if (head < 0) {  // If head is moving left out of bounds
                tape = extendTape(tape, false); // Add B at the start
                head = 0; // Adjust head position
            } else if (head >= tape.length) {  // If head is moving right out of bounds
                tape = extendTape(tape, true); // Add B at the end
            }
            
            if (state.equals("q12")) {
                tape = extendTape(tape, true); // Add B at the end
                break;
            }
            countSteps++;
        }
        //Final State
        String finalTape = new String(tape);
        System.out.println("Final Tape: " + finalTape);
        String finalTapeDiagram = getInputTape(finalTape);
        taFinalTape.setText(finalTapeDiagram);
        
        StringBuilder unaryProduct = new StringBuilder();
        for (char c : tape) {
            if (c == '1') {
                unaryProduct.append(c);
            }
        }
        String resultText = "";
        int product = decimalNum1 * decimalNum2;
        
        //Print results in console
        System.out.println("Equation: "+num1+"["+decimalNum1+"] * "+num2+"["+decimalNum2+"] = "+unaryProduct+"["+product+"]");
        System.out.println("Multiplication Result in Decimal: " + product);
        System.out.println("Multiplication Result in Unary: " + unaryProduct.toString());
        System.out.println("Steps: "+ countSteps + "\n");
        
        //Show results in GUI
        resultText += "Equation: "+num1+"["+decimalNum1+"] * "+num2+"["+decimalNum2+"] = "+unaryProduct+"["+product+"]\n";
        resultText += "Multiplication Result in Decimal: " + product + "\n";
        resultText += "Multiplication Result in Unary: " + unaryProduct.toString() + "\n";
        resultText += "Steps: "+ countSteps + "\n";
        taResult.setText(resultText);
        
        return null;
    }
    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Exit Program?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Exit Program?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            tfFirstNum.setText("");
            tfSecondNum.setText("");
            taInitialTape.setText("");
            taFinalTape.setText("");
            taResult.setText("");
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void tfSecondNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSecondNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSecondNumActionPerformed

    private void cmbOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOperationActionPerformed
        if (cmbOperation.getSelectedItem().toString().equalsIgnoreCase("+")){
            lblFirstNum.setText("First Number (in binary):");
            lblSecondNum.setText("Second Number (in binary):");
        }
        if (cmbOperation.getSelectedItem().toString().equalsIgnoreCase("*")){
            lblFirstNum.setText("First Number (in unary):");
            lblSecondNum.setText("Second Number (in unary):");
        }
    }//GEN-LAST:event_cmbOperationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new MainDashboard().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed
    
    private void designComponents() {
        // Set icon image for the program
        //ImageIcon img = new ImageIcon("src/icon.png");
        //this.setIconImage(img.getImage());
        // Center window when running
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2 - 25);
        this.setLocation(x, y);
    }
    
    private boolean isBinary(String num) {
        return num.matches("[01]+");
    }
    
    private boolean isUnary(String num) {
        return num.matches("[1]+");
    }
    
    private int getDecimalOfUnary(String num){
        int decimalNum = 0;
        for (int i = 0; i < num.length(); i++){
            decimalNum++;
        }
        return decimalNum;
    }
    
    private static char[] extendTape(char[] tape, boolean addAtEnd) {
        char[] newTape = new char[tape.length + 1];
        if (addAtEnd) {
            System.arraycopy(tape, 0, newTape, 0, tape.length);
            newTape[tape.length] = 'B';
        } else {
            System.arraycopy(tape, 0, newTape, 1, tape.length);
            newTape[0] = 'B';
        }
        return newTape;
    }
    
    private static String padLeftZeros(String binary, int length) {
        StringBuilder paddedBinary = new StringBuilder();
        for (int i = binary.length(); i < length; i++) {
            paddedBinary.append("0");
        }
        paddedBinary.append(binary);
        return paddedBinary.toString();
    }
    
    private static String getInputTape(String equation){
        char[] inputTape = equation.toCharArray();
        String tape = "";
        for (int i=0; i < equation.length(); i++){
            if (i == equation.length()-1)
                tape += inputTape[i];
            else
                tape += inputTape[i]+" | ";
        }
        return tape;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.registerCustomDefaultsSource("style");
        FlatLightLaf.setup();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TuringMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> cmbOperation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblFinalTape;
    private javax.swing.JLabel lblFirstNum;
    private javax.swing.JLabel lblInitialTape;
    private javax.swing.JLabel lblOperation;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblSecondNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTextArea taFinalTape;
    private javax.swing.JTextArea taInitialTape;
    private javax.swing.JTextArea taResult;
    private javax.swing.JTextField tfFirstNum;
    private javax.swing.JTextField tfSecondNum;
    private javax.swing.JLabel windowBg;
    // End of variables declaration//GEN-END:variables
}
